#!/bin/bash
# Note that the lines with $ are the qsub flags
# Execute from the current working directory
#$ -cwd
#
#  This is a long-running job so add this flag
#$ -l gpus=1
#$ -l inf
#
# Specify what folder to save outputs and errors
# Note that these directories can be the same
#$ -o output/
#$ -e error/
#
# If you want to get e-mail notification you can do the following
#$ -m abes
# Note that you do not need to add all the letters (abes) check link for detail

echo 'Starting job'

# Activate your Virtual environment
source /course/cs2952d/pytorch-gpu/bin/activate

echo 'Activated venv'

# Run your command
python3 main_orig.py --cuda

echo 'All done'